#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3_ex2(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, LCSG(KC_4), TG(4), KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_ESC, KC_A, KC_S, KC_D, KC_F, KC_G, LAG_T(KC_NO), LGUI(KC_SPC), KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_BSLS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_GRV, KC_LCTL, KC_LGUI, LT(1,KC_SPC), LT(2,KC_ENT), KC_RSFT, KC_RALT),
    [1] = LAYOUT_split_3x6_3_ex2(KC_TRNS, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_TRNS, KC_TRNS, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TRNS, KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_TRNS, KC_TRNS, KC_6, KC_7, KC_8, KC_9, KC_0, KC_PLUS, KC_PIPE, KC_MINS, KC_UNDS, KC_EQL, KC_LBRC, KC_RBRC, KC_LCBR, KC_RCBR, KC_LT, KC_GT, KC_QUES, KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, LT(3,KC_ENT), KC_TRNS, KC_TRNS),
    [2] = LAYOUT_split_3x6_3_ex2(KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, RSFT(KC_LEFT), RSFT(KC_DOWN), RSFT(KC_UP), RSFT(KC_RGHT), KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RSG(KC_LEFT), RSG(KC_DOWN), RSG(KC_UP), RSG(KC_RGHT), KC_NO, KC_NO, KC_TRNS, KC_TRNS, LT(3,KC_SPC), KC_TRNS, KC_TRNS, KC_TRNS),
    [3] = LAYOUT_split_3x6_3_ex2(QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RM_TOGG, RM_HUEU, RM_SATU, RM_VALU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RM_NEXT, RM_HUED, RM_SATD, RM_VALD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [4] = LAYOUT_split_3x6_3_ex2(KC_TAB, LSG(KC_LEFT), LSG(KC_DOWN), LSG(KC_UP), LSG(KC_RGHT), KC_H, KC_BSPC, TG(4), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_LALT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_LGUI, LT(5,KC_ENT), KC_NO, KC_NO, KC_NO),
    [5] = LAYOUT_split_3x6_3_ex2(KC_TRNS, KC_6, KC_7, KC_8, KC_0, LSG(KC_L), KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_K, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO)
};




#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


#ifdef RGB_MATRIX_ENABLE
static bool red_override_active = false;
static HSV  saved_hsv;

layer_state_t layer_state_set_user(layer_state_t state) {
    const uint8_t layer = get_highest_layer(state);

    if (layer == 4 || layer == 5) {
        if (!red_override_active) {
            saved_hsv = rgb_matrix_get_hsv();
        }

        red_override_active = true;

        // const HSV hsv = rgb_matrix_get_hsv();
        // rgb_matrix_sethsv_noeeprom(0, hsv.s, hsv.v);
        rgb_matrix_sethsv_noeeprom(0, 255, 180);
    } else if (red_override_active) {
        red_override_active = false;
        rgb_matrix_sethsv_noeeprom(saved_hsv.h, saved_hsv.s, saved_hsv.v);
    }

    return state;
}
#endif
